my_string = input('Какой сейчас год? ')
print(my_string, ' - 4 символа')
my_string = input('Кто говорит ГАВ? ')
print(my_string.upper())
my_string = input('Кто говорит мяу? ')
print(my_string.lower())
my_string = input('Напиши Фамилию и Имя: ')
print(my_string.replace(' ', ''), ', ой всё склеилось')
my_string = input('Какого цвета трава? ')
print(my_string[0])
my_string = input('Как дела? ')
print(my_string[-1])